In [1]:
%load_ext autoreload
%autoreload 2
import torch, rdkit
import sys, pathlib
from pathlib import Path
_THIS_FILE = Path(globals().get("__file__", Path.cwd())).resolve()
PROJECT_ROOT = _THIS_FILE.parent
sys.path.insert(0, str(PROJECT_ROOT))
from rdkit import Chem
from utils.utils import *
from utils.dataloader import dataset
from utils.generate import *
from pathlib import Path
device   = "cuda"
vocab = dataset.vocab
index_to_token = {idx: token for token, idx in vocab.items()}

{'[#C]': 0, '[#N]': 1, '[*H0]': 2, '[=*H0]': 3, '[=Branch]': 4, '[=C]': 5, '[=N]': 6, '[=O]': 7, '[=S]': 8, '[Branch]': 9, '[C]': 10, '[Cl]': 11, '[EOS]': 12, '[F]': 13, '[NH0+1]': 14, '[N]': 15, '[OH0-1]': 16, '[O]': 17, '[PAD]': 18, '[PH1]': 19, '[P]': 20, '[Ring1]': 21, '[Ring2]': 22, '[SOS]': 23, '[S]': 24, '[SiH0]': 25, '[pop]': 26}
27
tensor([ 2, 10, 17, 10,  2, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18])
tensor([23,  2, 10, 17, 10,  2, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18])
tensor([ 2, 10, 17, 10,  2, 12, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18])


[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValence(getExplicit=False)
[09:50:58] DEPRECATION WARNING: please use GetValen

In [2]:
def select_model(choice, latent):
    if choice == "Trans_MHA":
        from models.Trans_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)

    # Trans
    elif choice == "Trans":
        from models.Trans import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256_no_mha.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior_no_mha.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)
    # LSTM
    elif choice == "LSTM":
        from models.LSTM import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)


    # LSTM + MHA
    elif choice == "LSTM_MHA":
        from models.LSTM_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)
    

    return model, prior

In [3]:
def select_kernel(choice, model, prior, condition):
    condition = condition.repeat(1024, 1, 1)
    # Trans + MHA
    if choice == "Trans_MHA":
        mean, var = prior(condition.squeeze())
        z = model.reparameterize(mean, var)
        condition = model.input_embedding_p(condition)
        z_z = model.crossattn(z, condition, condition) * model.alpha + z
        z_prime = model.norm1(model.ff(z_z) + z_z)

    # Trans
    elif choice == "Trans":
        mean, var = prior(condition.squeeze())
        z_prime = model.reparameterize(mean, var)


    # LSTM
    elif choice == "LSTM":
        mu, lv = prior(condition.squeeze())
        z = model.reparameterize(mu, lv)
        z_prime = z

    # LSTM + MHA
    elif choice == "LSTM_MHA":
        mean, var = prior(condition.squeeze())
        z = model.reparameterize(mean, var)
        condition = model.input_embedding_p(condition)
        z_prime = model.ff(model.crossattn(z, condition, condition)) * model.alpha + z
        z_prime = model.norm1(model.ff(z_prime) + z_prime)
    
    return z_prime, condition

In [4]:
latent_dim = 128
condition = torch.tensor([21.0, -0.4, 1.4]).unsqueeze(-1).to(device) 
#condition = torch.tensor([0, -0.4, 1.4]).unsqueeze(-1).to(device)
mode = "Trans_MHA"
model, prior = select_model(mode, latent_dim)
z_prime, props = select_kernel(mode, model, prior, condition)

# 예시 호출 (z_prime는 shape [1, 265, 64]라고 가정)벡터
if mode =="Trans" or mode =="Trans_MHA":
    generated_tokens = generate_batch_sequence(model, z_prime, max_length=dataset.max_len+3,
                                        start_token=vocab['[SOS]'],
                                        end_token=vocab['[EOS]'],
                                        pad_token=vocab['[PAD]'],
                                        device=device)
elif mode=="LSTM": # LSTM
    generated_tokens = generate_batch_sequence_LSTM(model, z_prime, max_length=dataset.max_len+3,
                                                    start_token=vocab['[SOS]'],
                                                    end_token=vocab['[EOS]'],
                                                    pad_token=vocab['[PAD]'],
                                                    device=device, grammar_mask_fn=None,
                                                    index_to_token=index_to_token)
else:
    generated_tokens = generate_batch_sequence_LSTM_MHA(model, z=z_prime, max_length=dataset.max_len+3,
                                                        start_token=vocab['[SOS]'],
                                                        end_token=vocab['[EOS]'],
                                                        pad_token=vocab['[PAD]'],
                                                        grammar_mask_fn=None, index_to_token=index_to_token)
print("Generated token sequence:", generated_tokens)

Generated token sequence: [[23, 2, 10, 10, 17, 10, 10, 10, 17, 10, 10, 10, 10, 2, 12], [23, 2, 10, 10, 10, 10, 10, 10, 17, 10, 9, 2, 26, 10, 4, 7, 26, 17, 10, 2, 12], [23, 2, 10, 10, 10, 17, 10, 10, 13, 26, 13, 26, 10, 10, 10, 10, 10, 2, 12], [23, 2, 17, 10, 10, 10, 17, 10, 10, 10, 10, 2, 12], [23, 2, 17, 10, 17, 10, 9, 10, 17, 10, 10, 10, 17, 10, 4, 7, 26, 17, 10, 6, 17, 10, 2, 26, 10, 10, 21, 6, 26, 10, 12], [23, 2, 10, 17, 10, 10, 10, 2, 12], [23, 2, 10, 10, 10, 17, 10, 10, 17, 10, 17, 10, 10, 10, 2, 26, 6, 17, 10, 2, 12], [23, 2, 10, 10, 17, 10, 10, 6, 17, 10, 10, 10, 17, 10, 2, 12], [23, 2, 10, 17, 10, 10, 10, 17, 10, 10, 10, 10, 13, 26, 17, 10, 2, 12], [23, 2, 17, 10, 10, 10, 17, 10, 10, 17, 10, 10, 10, 10, 15, 10, 10, 10, 2, 12], [23, 2, 10, 10, 10, 17, 2, 12], [23, 2, 10, 10, 15, 10, 17, 10, 9, 10, 10, 10, 10, 17, 2, 26, 10, 17, 10, 10, 10, 2, 12], [23, 2, 10, 10, 10, 17, 15, 10, 17, 10, 2, 26, 10, 10, 6, 17, 10, 10, 17, 10, 10, 10, 10, 2, 12], [23, 2, 10, 17, 10, 10, 10, 17, 1

In [5]:
from rdkit import Chem, RDLogger
from rdkit.Chem import DataStructs, rdFingerprintGenerator
RDLogger.DisableLog('rdApp.error')


canbe = 0
notbe = 0
generated_smiles = []
for row in generated_tokens:
    del row[0]
    del row[-1]
    smiles = tok_ids_to_smiles(row, index_to_token)
    generated_smiles.append(smiles or "")

generated_smiles = [smiles.removesuffix("EOS").strip() for smiles in generated_smiles]

generator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def is_valid(smiles):
    return Chem.MolFromSmiles(smiles) is not None

TS = 0.0
canbe = 0
notbe = 0

for sm in generated_smiles:
    if(len(sm)==0):
        notbe += 1
        continue
    try:
        sm = PS(sm).canonicalize.psmiles
        if is_valid(sm):
            canbe += 1
            print(sm)
        else:
            notbe += 1
    except:
        notbe += 1
        continue

print("가능한 분자 개수 :", canbe)
print("불가능한 분자 개수 :", notbe)
print(canbe/(canbe+notbe))

[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:02] DEPRECATION WARNING: please use GetValence(which=)
[09:51:0

[*]CCCOCCCOCCC[*]
[*]CCOCCCOCC[*]
[*]COCCCOC(=O)OC=NOCOCOC([*])CCC
[*]CCOCC[*]
[*]=CCOCCCOCCCON=[*]
[*]CCNCCCOCCCOCCOCC[*]
[*]CCOC[*]
[*]CCCOCCC[*]
[*]CCCOCCC[*]
[*]CCOCCCOCC[*]
[*]COOC[*]
[*]CCOCOC[*]
[*]CO[*]
[*]COCCCOCC([*])COCCCCCCCCC#N
[*]COC[*]
[*]CCCOCC[*]
[*]CNOC[*]
[*]CCOCCOCC[*]
[*]CCOCCNC[*]
[*]CCOCOC[*]
[*]C[*]
[*]CCOCCOCC[*]
[*]CCOCOCOC[*]
[*]CCCCCOC([*])=O
[*]CCOCCCOCC[*]
[*]CCCOCOCNCC[*]
[*]C[*]
[*]CCOC[*]
[*]COC[*]
[*]=CCCCOCCOCCOCC=[*]
[*]C[*]
[*]CCOCOC[*]
[*]CCCOCCCCOCCOCCC[*]
[*]COC[*]
[*]CCOCC[*]
[*]CCCOCCOCC([*])=O
[*]CCOCCCOCC[*]
[*]CCOCOCC[*]
[*]CCOCCCOCOCC[*]
[*]CCOCCCOCC([*])=O
[*]CCCOCC[*]
[*]CCCOCCOCCC[*]
[*]CCCOCCOCCC[*]
[*]CCOCCOCC[*]
[*]COCCCCOC([*])=O
[*]CCCCCOCCCC[*]
[*]CCOC[*]
[*]#CCCOCCOCCOCC#[*]
[*]CCOCCCOCOCC[*]
[*]CCCOCCCCOCC[*]
[*]CCCCOCCCC[*]
[*]CCOCCOCOCC[*]
[*]COCCOCOC[*]
[*]CCCCCOCCCC[*]
[*]CCCOCCCCOCC[*]
[*]CCCCOCCC[*]
[*]C[*]
[*]CNC[*]
[*]CCCCOCCC[*]
[*]CCOCOCCOC[*]
[*]CCCOCCOCCOCCC[*]
[*]CCCOCOCC[*]
[*]CCOCCOCNC[*]
[*]CCCCCCOCCOCCCCC[*]
[*]C

In [6]:
from fcd_torch import FCD
from pathlib import Path

original_smiles = pd.read_csv(PROJECT_ROOT / "data/simulation-trajectory-aggregate_aligned.csv").iloc[:,1].values
calc       = FCD(device=device, n_jobs=8)

fcd_score  = calc(generated_smiles, original_smiles)
print(f"FCD = {fcd_score:.3f}")


FCD = 13.839
