In [1]:
%load_ext autoreload
%autoreload 2
import torch, rdkit
import sys, pathlib
from pathlib import Path
_THIS_FILE = Path(globals().get("__file__", Path.cwd())).resolve()
PROJECT_ROOT = _THIS_FILE.parent
sys.path.insert(0, str(PROJECT_ROOT))
from rdkit import Chem
from utils.utils import *
from utils.dataloader import dataset
from utils.generate import *
from pathlib import Path
device   = "cuda"
vocab = dataset.vocab
index_to_token = {idx: token for token, idx in vocab.items()}

{'[#Branch1]': 0, '[#Branch2]': 1, '[#C]': 2, '[#N]': 3, '[*]': 4, '[=*]': 5, '[=Branch1]': 6, '[=Branch2]': 7, '[=C]': 8, '[=N]': 9, '[=O]': 10, '[=S]': 11, '[Branch1]': 12, '[Branch2]': 13, '[C]': 14, '[Cl]': 15, '[EOS]': 16, '[F]': 17, '[N+1]': 18, '[N]': 19, '[O-1]': 20, '[O]': 21, '[PAD]': 22, '[PH1]': 23, '[P]': 24, '[Ring1]': 25, '[Ring2]': 26, '[SOS]': 27, '[S]': 28, '[Si]': 29}
30
tensor([ 4, 14, 21, 14,  4, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22])
tensor([27,  4, 14, 21, 14,  4, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22])
tensor([ 4, 14, 21, 14,  4, 16, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22])


In [2]:
def select_model(choice, latent):
    if choice == "Trans_MHA":
        from models.Trans_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)

    # Trans
    elif choice == "Trans":
        from models.Trans import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256_no_mha.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior_no_mha.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)
    # LSTM
    elif choice == "LSTM":
        from models.LSTM import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)


    # LSTM + MHA
    elif choice == "LSTM_MHA":
        from models.LSTM_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)
    

    return model, prior

In [3]:
def select_kernel(choice, model, prior, condition):
    condition = condition.repeat(1024, 1, 1)
    # Trans + MHA
    if choice == "Trans_MHA":
        mean, var = prior(condition.squeeze())
        z = model.reparameterize(mean, var)
        condition = model.input_embedding_p(condition)
        z_z = model.crossattn(z, condition, condition) * model.alpha + z
        z_prime = model.norm1(model.ff(z_z) + z_z)

    # Trans
    elif choice == "Trans":
        mean, var = prior(condition.squeeze())
        z_prime = model.reparameterize(mean, var)


    # LSTM
    elif choice == "LSTM":
        mu, lv = prior(condition.squeeze())
        z = model.reparameterize(mu, lv)
        z_prime = z

    # LSTM + MHA
    elif choice == "LSTM_MHA":
        mean, var = prior(condition.squeeze())
        z = model.reparameterize(mean, var)
        condition = model.input_embedding_p(condition)
        z_prime = model.ff(model.crossattn(z, condition, condition)) * model.alpha + z
        z_prime = model.norm1(model.ff(z_prime) + z_prime)
    
    return z_prime, condition

In [4]:
latent_dim = 128
condition = torch.tensor([21.0, -0.4, 1.4]).unsqueeze(-1).to(device) 
#condition = torch.tensor([0, 0.0, 0.0]).unsqueeze(-1).to(device)
mode = "Trans_MHA"
model, prior = select_model(mode, latent_dim)
z_prime, props = select_kernel(mode, model, prior, condition)

# 예시 호출 (z_prime는 shape [1, 265, 64]라고 가정)벡터
if mode =="Trans" or mode =="Trans_MHA":
    generated_tokens = generate_batch_sequence(model, z_prime, max_length=dataset.max_len+3,
                                        start_token=vocab['[SOS]'],
                                        end_token=vocab['[EOS]'],
                                        pad_token=vocab['[PAD]'],
                                        device=device)
elif mode=="LSTM": # LSTM
    generated_tokens = generate_batch_sequence_LSTM(model, z_prime, max_length=dataset.max_len+3,
                                                    start_token=vocab['[SOS]'],
                                                    end_token=vocab['[EOS]'],
                                                    pad_token=vocab['[PAD]'],
                                                    device=device, grammar_mask_fn=None,
                                                    index_to_token=index_to_token)
else:
    generated_tokens = generate_batch_sequence_LSTM_MHA(model, z=z_prime, max_length=dataset.max_len+3,
                                                        start_token=vocab['[SOS]'],
                                                        end_token=vocab['[EOS]'],
                                                        pad_token=vocab['[PAD]'],
                                                        grammar_mask_fn=None, index_to_token=index_to_token)
print("Generated token sequence:", generated_tokens)

Generated token sequence: [[27, 4, 14, 14, 14, 21, 14, 14, 14, 21, 14, 12, 14, 14, 21, 14, 4, 14, 2, 14, 14, 14, 14, 14, 14, 16], [27, 4, 21, 14, 14, 14, 14, 14, 21, 14, 14, 4, 21, 14, 12, 14, 14, 21, 14, 14, 14, 14, 14, 14, 14, 21, 14, 16], [27, 4, 21, 14, 14, 14, 21, 14, 21, 14, 14, 14, 14, 12, 14, 4, 14, 21, 25, 14, 14, 14, 14, 4, 14, 1, 14, 16], [27, 4, 14, 14, 14, 14, 14, 14, 19, 14, 6, 14, 10, 14, 21, 14, 3, 14, 14, 14, 4, 21, 14, 21, 14, 2, 14, 16], [27, 4, 14, 21, 14, 14, 14, 21, 14, 21, 14, 12, 25, 14, 21, 14, 6, 14, 10, 21, 14, 4, 14, 14, 14, 21, 14, 16], [27, 4, 14, 14, 14, 14, 14, 14, 21, 14, 21, 25, 16], [27, 4, 14, 14, 21, 14, 14, 21, 14, 4, 14, 14, 19, 14, 19, 14, 3, 14, 14, 14, 14, 14, 14, 4, 14, 14, 14, 16], [27, 4, 14, 14, 14, 14, 14, 2, 14, 14, 19, 12, 0, 4, 19, 14, 21, 14, 14, 14, 3, 14, 14, 14, 12, 14, 14, 4, 16], [27, 4, 14, 21, 14, 14, 4, 14, 14, 14, 14, 14, 14, 17, 8, 12, 14, 4, 10, 14, 21, 14, 14, 14, 14, 14, 14, 16], [27, 4, 14, 14, 14, 14, 21, 14, 4, 14, 21, 

In [5]:
from rdkit import Chem, RDLogger
from rdkit.Chem import DataStructs, rdFingerprintGenerator
RDLogger.DisableLog('rdApp.error')


canbe = 0
notbe = 0
generated_smiles = []
for row in generated_tokens:
    del row[0]
    del row[-1]
    smiles = tok_ids_to_smiles(row, index_to_token)
    generated_smiles.append(smiles or "")

generated_smiles = [smiles.removesuffix("EOS").strip() for smiles in generated_smiles]

generator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def is_valid(smiles):
    return Chem.MolFromSmiles(smiles) is not None

TS = 0.0
canbe = 0
notbe = 0
valid_generated_smiles = []
for sm in generated_smiles:
    if(len(sm)==0):
        notbe += 1
        continue
    try:
        sm = PS(sm).canonicalize.psmiles
        if is_valid(sm):
            canbe += 1
            if sm not in valid_generated_smiles:
                print(sm)
                valid_generated_smiles.append(sm)
        else:
            notbe += 1
    except:
        notbe += 1
        continue

print("가능한 분자 개수 :", canbe)
print("불가능한 분자 개수 :", notbe)
print(canbe/(canbe+notbe))

[*]OCCCCOCCCOC([*])C
[*]CCCOCCOCC[*]
[*]CCCOCOCCCOC([*])C=O
[*]OCCOCCCOCOC(CO)C([*])=O
[*]CCOCCOC[*]
[*]CCC#CCCCCN([*])C#N
[*]CCOC[*]
[*]CCCOCC[*]
[*]C[*]
[*]CCCCOCOCCC[*]
[*]OCCCCNOCCCCOC([*])=O
[*]CCCCCCOC(=O)C([*])C
[*]OCCCCOCCCOC([*])CCCCCOCCC=CC
[*]CCOCC[*]
[*]CCCOC([*])C
[*]CCCOCCCCOCCOCCC[*]
[*]CCSC[*]
[*]CCCOCOOCOCPCOCCOCC[*]
[*]CCCCCCCOCCCCSCC([*])C
[*]COC[*]
[*]CCCOCCCOCOOCCC[*]
[*]CCCOCCCCOCCC[*]
[*]CCCCOCCC[*]
[*]OCOCCCCCCCOCCCOCC(=O)OC([*])C
[*]CCOCCOCCOC[*]
[*]CCCCCNCCCC[*]
[*]CCCCCOCCCC[*]
[*]CCOCCNOCOCCOCC[*]
[*]CCCCCCCNC(Cl)CC([*])=O
[*]CCCCOCCCOCC([*])C=NCCCC
[*]CCCOOCCOCC[*]
[*]CCCCOC([*])O
[*]CCCCCCCOCC#CCCNCCC([*])C
[*]OCCCCCCCCCC=NCOC([*])=O
[*]CCCCCOC([*])=O
[*]NCCCCOC([*])=O
[*]CCCOCCOCCNOCCOCCC[*]
[*]COCCNCOC([*])=O
[*]COCOC[*]
[*]CCNCCOCCC([*])O[PH](=O)CCF
[*]CCCNCCCCOCCC[*]
[*]COCCOCNC([*])=O
[*]CCCNOCCCCCOCCC[*]
[*]CCCCOCCCOCCC[*]
[*]CCCOCCC[*]
[*]CO[*]
[*]CCCONCCOCCCCNCC[*]
[*]CCCOCCCCCCCCCNC([*])C
[*]CCCCOCCOCCOCCC[*]
[*]CCNCCOCC[*]
[*]CCNCCOCCOCC[*]
[*]CC

In [6]:
from fcd_torch import FCD
from pathlib import Path

original_smiles = pd.read_csv(PROJECT_ROOT / "data/simulation-trajectory-aggregate_aligned.csv").iloc[:,1].values
calc       = FCD(device=device, n_jobs=8)
original_top10p = original_smiles[:int(len(original_smiles)*0.1)]
print(len(original_top10p))
fcd_score  = calc(valid_generated_smiles, original_smiles)
print(f"FCD = {fcd_score:.3f}")

print(f"FCD of top 10% of orignial smiles : {calc(valid_generated_smiles, original_top10p)}")

627
FCD = 12.645
FCD of top 10% of orignial smiles : 8.16996542856551
