In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2
import torch, rdkit
from pathlib import Path, sys
_THIS_FILE = Path(globals().get("__file__", Path.cwd())).resolve()
PROJECT_ROOT = _THIS_FILE.parent
sys.path.insert(0, str(PROJECT_ROOT))
from rdkit import Chem
from utils.utils import *
from utils.dataloader import *
from utils.loss_fn import *
from utils.eval import *

from tqdm import trange
device   = "cuda"
test = sfp.encoder_psmiles("CC(CCCNC(=O)C(C)OC(=O)[*])O[*]")
print(test)
print(list(sfp.split_selfies(test)))
vocab = dataset.vocab
index_to_token = {idx: token for token, idx in vocab.items()}

{'[#Branch1]': 0, '[#Branch2]': 1, '[#C]': 2, '[#N]': 3, '[*]': 4, '[=*]': 5, '[=Branch1]': 6, '[=Branch2]': 7, '[=C]': 8, '[=N]': 9, '[=O]': 10, '[=S]': 11, '[Branch1]': 12, '[Branch2]': 13, '[C]': 14, '[Cl]': 15, '[EOS]': 16, '[F]': 17, '[N+1]': 18, '[N]': 19, '[O-1]': 20, '[O]': 21, '[PAD]': 22, '[PH1]': 23, '[P]': 24, '[Ring1]': 25, '[Ring2]': 26, '[SOS]': 27, '[S]': 28, '[Si]': 29}
30
tensor([ 4, 14, 21, 14,  4, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22])
tensor([27,  4, 14, 21, 14,  4, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22])
tensor([ 4, 14, 21, 14,  4, 16, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22])
[C][C][Branch2][Ring1][Ring1][C][C][C][N][C][=Branch1][C][=O][C][Branch1][C][C][O][C][=B

In [2]:
def select_model(choice, latent):
    if choice == "Trans_MHA":
        from models.Trans_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda()
        model.decoder.cuda()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda()

    # Trans
    elif choice == "Trans":
        from models.Trans import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda()

    # LSTM
    elif choice == "LSTM":
        from models.LSTM import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda()
        model.decoder.cuda()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda()

    # LSTM + MHA
    elif choice == "LSTM_MHA":
        from models.LSTM_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda()
        model.decoder.cuda()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda()

    return model, prior

def get_loss_fn(choice, latent):
    if choice == "Trans_MHA":
        loss_fn = ConditionalVAELoss(
            vocab_size=dataset.vocab_size,
            max_beta=0.9,
            anneal_steps=300,
            cyc_steps=600,
            num_cycles=2,
            free_bits=0.06,
            capacity_max=int(0.5*latent),
            capacity_inc=0.01,
            gamma=5.0,
            prop_w=0.02,
            nce=0.03,
            sig_pen_p=0.001,
            sig_pen_q=0.002,
            imb=0.1,
            latent_dim=latent
        ).cuda()

    # Trans
    elif choice == "Trans":
        loss_fn = ConditionalVAELoss(
            vocab_size=dataset.vocab_size,
            max_beta=1.0,
            anneal_steps=300,
            cyc_steps=600,
            num_cycles=2,
            free_bits=0.06,
            capacity_max=int(0.5*latent),
            capacity_inc=0.01,
            gamma=5.0,
            prop_w=0.02,
            nce=0.03,
            sig_pen_p=0.001,
            sig_pen_q=0.002,
            imb=0.1,
            latent_dim=latent
        ).cuda()

    # LSTM
    elif choice == "LSTM":
        loss_fn = ConditionalVAELoss_LSTM(
            vocab_size=dataset.vocab_size,
            max_beta=0.5,
            anneal_steps=300,
            cyc_steps=600,
            num_cycles=2,
            free_bits=0.8,
            capacity_max=int(0.5*latent),
            capacity_inc=0.01,
            gamma=5.0,
            prop_w=0.02,
            nce=0.03,
            sig_pen_p=0.001,
            sig_pen_q=0.002,
            imb=0.1,
            latent_dim=latent
        ).cuda()

    # LSTM + MHA
    elif choice == "LSTM_MHA":
        loss_fn = ConditionalVAELoss(
            vocab_size=dataset.vocab_size,
            max_beta=1.0,
            anneal_steps=300,
            cyc_steps=600,
            num_cycles=2,
            free_bits=0.04,
            capacity_max=int(0.5*latent),
            capacity_inc=0.01,
            gamma=5.0,
            prop_w=0.02,
            nce=0.03,
            sig_pen_p=0.001,
            sig_pen_q=0.002,
            imb=0.1,
            latent_dim=latent
        ).cuda()
        
    return loss_fn

In [3]:
mode = "LSTM_MHA"
latent_dim = 128
seq_len = dataset.max_len+3
model, prior = select_model(mode, latent_dim)
loss_fn = get_loss_fn(mode, latent_dim)

for head in [model.to_prop, model.to_prop_z]:
    nn.init.xavier_uniform_(head.weight)
    nn.init.zeros_(head.bias)

prior_params = prior.parameters()


prop_params = list(model.to_prop.parameters())+list(model.to_prop_z.parameters())
prop_params_id = {id(p) for p in prop_params}
base_params = [p for p in model.parameters() if id(p) not in prop_params_id]

lr = 3e-4
lr_prior = lr*0.1
from torch.optim import AdamW
optim = AdamW([{'params':base_params, 'lr':lr},{'params':prop_params, 'lr':lr*0.5}])
optim2 = AdamW(prior_params, lr=lr_prior)

In [4]:
import datetime
from rdkit import Chem, RDLogger
RDLogger.DisableLog('rdApp.error')
status_out = widgets.Output()
PAD_IDX = dataset.vocab['[PAD]']
display(status_out)
epoch = 1200
model.train()
progress = tqdm(range(epoch), desc="Training")
loss_arr=[]

for i in progress:
    log_var_extract=[]
    log_var_p_extract = []
    batchloss = 0.0
    embeddings = []
    mean_extract = []
    results = []
    iwaes_eval = []
    ess_eval = []
    ess_len_eval = []
    ess_latent_eval = []
    count = 0
    kld_raw_batch = 0.0
    bce = 0.0
    kld = 0.0
    model.train()
    if mode=="Trans" or mode=="Trans_MHA":
      for batch in train_dataloader:
        sm_enc, sm_dec_in, sm_dec_out, prop = [t.to(device) for t in batch]
        optim.zero_grad()
        optim2.zero_grad()

        enc_mask = sm_enc==PAD_IDX
        dec_mask = sm_dec_in==PAD_IDX

        output, tgt, mu_q, lv_q, tgt_z = model.forward(sm_enc, sm_dec_in, prop.float(), enc_mask, dec_mask)


        
        mu_p, lv_p = prior.forward(prop.squeeze())
        with torch.no_grad():
          log_var_extract.append(torch.exp(0.5 * lv_q.cpu()).to(device))
          log_var_p_extract.append(torch.exp(0.5 * lv_p.cpu()).to(device))
          mean_extract.append(mu_q.cpu())
        
        loss, BCE, KLD, kld_raw, kld_per_token, props = loss_fn.forward(output.float(),
                                sm_dec_out,
                                mu_q, lv_q, mu_p, lv_p,
                                tgt, prop.float().squeeze(), tgt_z,
                                i)
        
        results.append(output)

        loss.backward()
        optim.step()
        optim2.step()

        batchloss += loss.item()
        kld_raw_batch += kld_raw.item()
        bce += BCE.item()
        kld += KLD.item()
        count +=1

      #################EVAL#################
      model.eval()
      with torch.no_grad(), torch.inference_mode():
        for batch in val_dataloader:
            sm_enc_, sm_dec_in_, sm_dec_out_, prop_ = [t.to(device) for t in batch]
            smi_mask = sm_enc_==PAD_IDX
            iwae_b, ess_b, ess_len, ess_latent = eval_iwae_bound(model, prior, sm_enc_, sm_dec_in_, sm_dec_out_, prop_, smi_mask, K=64, chunk=8)
            iwaes_eval.append(iwae_b)
            ess_eval.append(ess_b)
            ess_len_eval.append(ess_len)
            ess_latent_eval.append(ess_latent)

    else:
      for batch in train_dataloader_LSTM:
        model.train()
        tf_ratio = max(0.0, 1.0 - i / 300)
        optim.zero_grad()
        optim2.zero_grad()
        
        [sm_dec_in, sm_dec_out, prop] = [t.to(device) for t in batch]
        output, tgt, mu_q, lv_q, tgt_z = model(sm_dec_in, sm_dec_out, prop.float())

        mu_p, lv_p = prior.forward(prop.float().squeeze())
        with torch.no_grad():
          log_var_extract.append(torch.exp(0.5 * lv_q.cpu()).to(device))
          log_var_p_extract.append(torch.exp(0.5 * lv_p.cpu()).to(device))
          mean_extract.append(mu_q.cpu())
        loss, BCE, KLD, kld_raw, kld_per_token, props = loss_fn.forward(output.float(),
                                sm_dec_out,
                                mu_q, lv_q, mu_p, lv_p,
                                tgt, prop.float().squeeze(), tgt_z,
                                i)
        
        loss.backward()
        optim.step()
        optim2.step()

        batchloss += loss.item()
        kld_raw_batch += kld_raw.item()
        bce += BCE.item()
        kld += KLD.item()
        count += 1
      #################EVAL#################
      model.eval()
      with torch.no_grad(), torch.inference_mode():
        if mode=="LSTM":
          for batch in val_dataloader_LSTM:
            sm_dec_in_, sm_dec_out_, prop_ = [t.to(device) for t in batch]
            iwae_b, log_ws = iwae_bound_lstm(model, prior, sm_dec_in_, sm_dec_out_, prop_, K=64, chunk=8, pad_idx=PAD_IDX)
            iwaes_eval.append(iwae_b.mean().cpu().numpy())
            ess_eval.append(compute_ess(log_ws.mean().detach().cpu(), dim=0))
        else:
          for batch in val_dataloader_LSTM:
            sm_dec_in_, sm_dec_out_, prop_ = [t.to(device) for t in batch]
            iwae_b, log_ws = iwae_bound_lstm_MHA(model, prior, sm_dec_in_, sm_dec_out_, prop_, K=64, chunk=8, pad_idx=PAD_IDX)
            iwaes_eval.append(iwae_b.mean().cpu().numpy())
            ess_eval.append(compute_ess(log_ws.mean().detach().cpu(), dim=0))
        
    #Loss 값 추가
    loss = batchloss / len(train_dataloader)
    loss_arr.append(loss)

    # 진행 바의 속성으로부터 필요한 값들 추출 (예시)
    elapsed = int(progress.format_dict.get("elapsed", 0))
    formatted_elap = str(datetime.timedelta(seconds=elapsed))
    rate = progress.format_dict.get("rate", None)
    sec_per_iter = 1 / rate if rate and rate != 0 else 0
    total = int(sec_per_iter * progress.total)
    formatted_total = str(datetime.timedelta(seconds=total))

    mu_ext = torch.cat(mean_extract, dim=0).view(-1, latent_dim)
    mu_perdim_std = mu_ext.std(dim=0, unbiased=False).numpy().mean()
    mu_std = mu_ext.std(unbiased=False).item()

    lv_q_ext = torch.cat(log_var_extract)
    lv_q_mu = lv_q_ext.mean().item()
    lv_q_std = lv_q.std().mean()

    lv_p_ext = torch.cat(log_var_p_extract)
    lv_p_mu = lv_p_ext.mean().item()
    lv_p_std = lv_p.std().mean()

    # 고정된 상태 정보를 업데이트 (Output 위젯에 출력)
    with status_out:
        clear_output(wait=True)
        print(f"🔹 Elapsed: {formatted_elap} | sec/iter: {sec_per_iter:.3f}s")
        print("🔹 Total time: ", formatted_total)
        print(f"🔹 Step: {i+1}/{progress.total}")
        print(f"🔹 loss: {loss:0.6f}, BCE: {BCE/seq_len:.6f}, KLD: {KLD/seq_len:.6f}")
        print(f"Raw KLD: {kld_raw_batch/len(train_dataloader):.6f}")
        print(f"[Posterior] sigma mean : {lv_q_mu:0.6f}, sigma std : {lv_q_std:0.6f}")
        print(f"[Prior]     sigma mean : {lv_p_mu:0.6f}, sigma std : {lv_p_std:0.6f}")
        print(f"Posterior μ per-dim std: {mu_perdim_std:0.6f}")
        print(f"Posterior μ overall std: {mu_std:0.6f}")
        print(f"[EVAL] iwae : {np.mean(iwaes_eval):.6f}, ESS : {np.mean(ess_eval):0.6f}, {np.mean(ess_len_eval):.6f}, {np.mean(ess_latent_eval):.6f}")
        # print(f"alpha: {model.alpha.item():.6f}")

Output()

Training:   0%|          | 0/1200 [00:00<?, ?it/s]

In [5]:
try:
    print(model.alpha)
except:
    print("no alpha")

Parameter containing:
tensor([0.8180], device='cuda:0', requires_grad=True)


In [6]:
model.eval()
prior.eval()
results = []
origin = []

properties_results=[]
properties_origin=[]
print(len(val_dataset))
with torch.no_grad():
    if mode == "Trans" or mode == "Trans_MHA":
        for (smiles_enc, smiles_dec_input, smiles_dec_output, properties) in val_dataloader:
            B = smiles_enc.size(0)

            smiles_enc = smiles_enc.to(device)
            smiles_dec_input = smiles_dec_input.to(device)
            smiles_dec_output = smiles_dec_output.to(device)
            properties = properties.to(device)
            
            enc_smi_mask = smiles_enc==PAD_IDX
            dec_smi_mask = smiles_dec_input==PAD_IDX

            result, tgt, means, log_var, z = model(smiles_enc, smiles_dec_input, properties, enc_smi_mask, dec_smi_mask)
            # result = model.deocder(smiles_dec_input, means.view(B, -1, latent_dim))
            # result = model.predict(result)

            results.append(result)
            origin.append(smiles_dec_output)

            properties_results.append(tgt)
            properties_origin.append(properties)
    else:
        for batch in val_dataloader_LSTM:
            [sm_dec_in, sm_dec_out, prop] = [t.to(device) for t in batch]
            output, tgt, mu_q, lv_q, tgt_z = model.forward(sm_dec_in, sm_dec_out, prop.float())

            mu_p, lv_p = prior.forward(prop.float().squeeze())

            results.append(output)
            origin.append(sm_dec_out)

            properties_results.append(tgt)
            properties_origin.append(prop)

results = torch.cat(results, dim=0)
origin = torch.cat(origin, dim=0)
results = nn.functional.softmax(results, dim=-1) 
argmax_indices = torch.argmax(results, dim=-1)
output = torch.nn.functional.one_hot(argmax_indices, num_classes=results.size(-1))
print(argmax_indices)
print(results.shape)
print(origin.shape)

from sklearn.metrics import mean_absolute_error
properties_origin=torch.cat(properties_origin,dim=0)
properties_results=torch.cat(properties_results,dim=0)
MAE_2 = mean_absolute_error(properties_origin.squeeze().cpu(), properties_results.squeeze().cpu())
print("MAE(properties) : ", MAE_2)


results_smiles = []
origin_smiles = []

for row in argmax_indices:
    smiles = tok_ids_to_smiles(row.tolist(), index_to_token)
    results_smiles.append(smiles or "")

for row in origin:
    smiles = tok_ids_to_smiles(row.tolist(), index_to_token)
    origin_smiles.append(smiles or "")

1567


tensor([[ 4, 14, 14,  ..., 16, 16, 16],
        [ 4, 19, 14,  ..., 16, 16, 16],
        [ 4, 21, 14,  ..., 16, 16, 16],
        ...,
        [ 4, 19, 14,  ..., 26, 26, 25],
        [ 4, 14, 19,  ..., 16, 16, 16],
        [ 4, 14, 21,  ..., 16, 16, 16]], device='cuda:0')
torch.Size([1567, 37, 30])
torch.Size([1567, 37])
MAE(properties) :  0.15921957790851593
[decode_keep_star] SELFIES: [*][C][C][Branch1][C][C][O][C][=Branch1][C][=O][O][C][C][Branch1][C][C][N][Branch1][C][*][C][C][O][C]
[decode_keep_star] SMILES : *CC(C)OC(=O)OCC(C)N(*)CCOC
[decode_keep_star] SELFIES: [*][N][C][=Branch1][C][=O][O][C][Branch1][C][C][C][Branch1][C][*][C][C][C][C][C][C][C][C][C]
[decode_keep_star] SMILES : *NC(=O)OC(C)C(*)CCCCCCCCC
[decode_keep_star] SELFIES: [*][O][C][=Branch1][C][=O][O][C][C][C][C][C][N][C][=Branch1][C][=O][C][Branch1][C][*][Branch1][C][C][C][C]
[decode_keep_star] SMILES : *OC(=O)OCCCCCNC(=O)C(*)(C)CC
[decode_keep_star] SELFIES: [*][C][N][C][=Branch1][C][=O][N][C][C][C][N][C][=Branch1][C]

In [7]:
origin_smiles = [smiles.removesuffix("EOS").strip() for smiles in origin_smiles]
results_smiles = [smiles.removesuffix("EOS").strip() for smiles in results_smiles]

for i in range(len(results_smiles)):
    if(origin_smiles[i] != results_smiles[i]):
        print(i, "번째 다름!")
    print("real smiles      : ", origin_smiles[i])
    print("predicted smiles : ", results_smiles[i])


MAE = mean_absolute_error(origin.cpu(), torch.argmax(results.cpu(), dim=-1))
print("MAE : ", MAE)



0 번째 다름!
real smiles      :  [*]CC(C)OC(=O)OCC(C)N([*])CCC
predicted smiles :  [*]CC(C)OC(=O)OCC(C)N([*])CCOC
1 번째 다름!
real smiles      :  [*]NC(=O)OC(CC)C([*])C(=O)OCC
predicted smiles :  [*]NC(=O)OC(C)C([*])CCCCCCCCC
2 번째 다름!
real smiles      :  [*]OC(=O)OCC(C)NC(=O)C(C)C([*])CC
predicted smiles :  [*]OC(=O)OCCCCCNC(=O)C([*])(C)CC
3 번째 다름!
real smiles      :  [*]CNC(=O)CCCCNC(=O)NC([*])CC
predicted smiles :  [*]CNC(=O)NCCCNC(=O)NC([*])CC
4 번째 다름!
real smiles      :  [*]COC(=O)NC([*])C(=O)NCCCC
predicted smiles :  [*]COC(=O)NC([*])C(=O)OCC
5 번째 다름!
real smiles      :  [*]CNC(=O)COC(=O)OCC([*])C(C)C
predicted smiles :  [*]CNC(=O)COOC(=O)OC([*])C
6 번째 다름!
real smiles      :  [*]OC(=O)OCC(O)=C(O)C([*])C=O
predicted smiles :  [*]OC(=O)OC(C(=O)OO)C([*])C(=O)ON
7 번째 다름!
real smiles      :  [*]COC(=O)OCCCCC(=O)NC([*])C=C
predicted smiles :  [*]COC(=O)OCCOCC(=O)NC([*])C=C
8 번째 다름!
real smiles      :  [*]CN(C)CCCNC(=O)OC([*])CSC
predicted smiles :  [*]CN(C)CCCOC(=O)OC([*])CCCC=C
9 번째 다름!
real 

In [8]:
from rdkit import Chem, RDLogger
from rdkit.Chem import DataStructs, rdFingerprintGenerator
RDLogger.DisableLog('rdApp.error')

generator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def tanimoto_similarity(smiles1, smiles2):
    mol1 = Chem.MolFromSmiles(smiles1)
    mol2 = Chem.MolFromSmiles(smiles2)
    fp1 = generator.GetFingerprint(mol1)
    fp2 = generator.GetFingerprint(mol2)
    return DataStructs.TanimotoSimilarity(fp1, fp2)

def is_valid(smiles):
    return Chem.MolFromSmiles(smiles) is not None

TS = 0.0
canbe = 0
notbe = 0

for sm, orig in zip(results_smiles, origin_smiles):
    if(len(sm)==0):
        notbe += 1
        continue
    try:
        sm = PS(sm).canonicalize.psmiles
        if is_valid(sm) and is_valid(orig):
            sim = tanimoto_similarity(sm, orig)
            TS += sim
            canbe += 1
        else:
            notbe += 1
    except:
        notbe += 1
        continue


if canbe > 0:
    print("Tanimoto Similarity : ", TS / canbe)
else:
    print("No valid molecules to compare.")

print("가능한 분자 개수 :", canbe)
print("불가능한 분자 개수 :", notbe)
print("Valid fraction      :", canbe / len(results_smiles))


Tanimoto Similarity :  0.5083454795340134
가능한 분자 개수 : 1475
불가능한 분자 개수 : 92
Valid fraction      : 0.9412890874282067


In [9]:
def save_weights(choice):
    if choice == "Trans_MHA":
        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256.pth")
        torch.save(model.state_dict(), save_path)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior.pth")        
        torch.save(prior.state_dict(), save_path)

    # Trans
    elif choice == "Trans":
        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256_no_mha.pth")
        torch.save(model.state_dict(), save_path)

    # LSTM
    elif choice == "LSTM":
        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM.pth")        
        torch.save(model.state_dict(), save_path)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_prior.pth")       
        torch.save(prior.state_dict(), save_path)


    # LSTM + MHA
    elif choice == "LSTM_MHA":
        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA.pth")        
        torch.save(model.state_dict(), save_path)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA_prior.pth")        
        torch.save(prior.state_dict(), save_path)

def select_model(choice, latent):
    if choice == "Trans_MHA":
        from models.Trans_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)

    # Trans
    elif choice == "Trans":
        from models.Trans import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_dmodel256_no_mha.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_prior_no_mha.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)
    # LSTM
    elif choice == "LSTM":
        from models.LSTM import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()
        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)


    # LSTM + MHA
    elif choice == "LSTM_MHA":
        from models.LSTM_MHA import CVAE, PriorNet
        model    = CVAE(latent_dim=latent).cuda().eval()
        model.decoder.cuda().eval()


        prior = PriorNet(y_dim=3, latent_dim=latent).cuda().eval()

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA.pth")
        state_dict = torch.load(save_path)
        model.load_state_dict(state_dict)

        save_path = (PROJECT_ROOT / "models/weights" / "model_weights_LSTM_MHA_prior.pth")
        state_dict = torch.load(save_path)
        prior.load_state_dict(state_dict)
    

    return model, prior

In [10]:
save_weights(mode)

In [11]:
# 1) 길이 페널티 키워서 긴 후보 선호
print(reconstruct_zmu(model, val_dataloader, dataset.vocab,
                      beam_width=30, len_penalty=1.0, temperature=0.80,
                      max_len=dataset.max_len+3))

# 150/8 -> 0.4704

TypeError: LSTM.forward() takes from 2 to 3 positional arguments but 4 were given